site_name: A Python SDK for Jellyfin.
site_url: https://jellyfin-sdk-python.github.io
site_author: Webysther Sperandio
site_description: A Python SDK for interacting with the Jellyfin API.

nav:
  - About: index.md
  - API 10.11: api_10_11/README.md
  - API 10.10: api_10_10/README.md

extra_css:
  - css/custom.css

theme:
  name: readthedocs
  highlightjs: true
  hljs_languages:
    - yaml
    - python
